apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app: leaderz
  name: leaderz

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: leaderz
  name: leaderz
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: leaderz
  name: leaderz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leaderz
subjects:
  - kind: ServiceAccount
    name: leaderz
